source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yusuga/Specs.git'

platform :ios, '7.0'

target 'TestUIImageFiliters' do
  pod 'NYXImagesKit'
  pod 'GPUImage'
  pod 'NSRunLoop+PerformBlock'
  pod 'YSUIKitAdditions'
  pod 'YSProcessTimer'

  target 'TestUIImageFilitersTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
