//
//  ImageFilterStyleKit.h
//  YSImageFilter
//
//  Created by Yu Sugawara on 2014/06/22.
//  Copyright (c) 2014 Picos LLC.. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface ImageFilterStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* earthTargets;

// Generated Images
+ (UIImage*)imageOfEarth;

@end
